(function () {
// ============================================================
// DATA: CATEGORIES & WORDS
// ============================================================
const CATEGORIES = [
  {
    id: 'chakula',
    name: 'Vyakula vya Tanzania',
    sub: 'Tanzania Food',
    icon: '🍽️',
    color: '#FF7043',
    words: [
      { sw: 'UGALI', en: 'Maize porridge / staple meal', ex: 'Ninakula ugali na samaki kila siku.', note: 'Ugali ni chakula kikuu cha Tanzania.' },
      { sw: 'PILAU', en: 'Spiced rice with meat', ex: 'Pilau ya Zanzibar ni tamu sana.', note: 'Pilau ina viungo vingi kama karafuu na pilipili manga.' },
      { sw: 'WALI', en: 'Cooked rice', ex: 'Ninapenda wali na maharage.', note: 'Wali ni chakula cha kawaida pwani.' },
      { sw: 'NYAMA', en: 'Meat', ex: 'Ananunua nyama sokoni asubuhi.' },
      { sw: 'SAMAKI', en: 'Fish', ex: 'Samaki wa Ziwa Victoria ni mkubwa sana.' },
      { sw: 'NDIZI', en: 'Banana / plantain', ex: 'Ndizi za Tanzania ni tamu.', note: 'Ndizi za kupika ni tofauti na ndizi za kula moja kwa moja.' },
      { sw: 'CHIPSI', en: 'French fries / chips', ex: 'Watoto wanakula chipsi baada ya shule.' },
      { sw: 'MAHARAGE', en: 'Beans', ex: 'Maharage na wali ni mlo wa pamoja.' },
      { sw: 'MCHICHA', en: 'Spinach / leafy greens', ex: 'Mama anapika mchicha na nyanya.' },
      { sw: 'KACHUMBARI', en: 'Fresh tomato and onion salad', ex: 'Kachumbari ina nyanya, kitunguu na limau.' },
      { sw: 'MANDAZI', en: 'Fried dough bread', ex: 'Mandazi na chai ni kifungua kinywa kizuri.' },
      { sw: 'SUPU', en: 'Soup / broth', ex: 'Supu ya nyama inanipa nguvu.' },
    ]
  },
  {
    id: 'miji',
    name: 'Miji na Maeneo',
    sub: 'Cities & Places',
    icon: '🏙️',
    color: '#42A5F5',
    words: [
      { sw: 'DODOMA', en: 'Capital city of Tanzania', ex: 'Dodoma ni mji mkuu wa Tanzania.', note: 'Dodoma imekuwa mji mkuu rasmi tangu 1996.' },
      { sw: 'ARUSHA', en: 'Major city near Kilimanjaro', ex: 'Tunaenda Arusha kuona wanyama.', note: 'Arusha ni lango la safari nyingi.' },
      { sw: 'MWANZA', en: 'City on Lake Victoria', ex: 'Mwanza iko kandoni mwa Ziwa Victoria.' },
      { sw: 'MBEYA', en: 'City in Southern Highlands', ex: 'Mbeya ina hali ya hewa ya baridi.', note: 'Mbeya inajulikana kwa kilimo cha chai na kahawa.' },
      { sw: 'TANGA', en: 'Coastal city in northeastern Tanzania', ex: 'Tanga ina pwani nzuri sana.' },
      { sw: 'KIGOMA', en: 'City on Lake Tanganyika', ex: 'Kigoma ipo karibu na Ziwa Tanganyika.' },
      { sw: 'MOSHI', en: 'City at foot of Kilimanjaro', ex: 'Moshi iko chini ya Mlima Kilimanjaro.' },
      { sw: 'MOROGORO', en: 'City with Uluguru Mountains', ex: 'Morogoro ina milima mizuri ya Uluguru.' },
      { sw: 'ZANZIBAR', en: 'Island famous for spices', ex: 'Zanzibar inajulikana kwa viungo na pwani.', note: 'Zanzibar ni sehemu ya Jamhuri ya Muungano wa Tanzania.' },
      { sw: 'DARESSALAAM', display: 'Dar es Salaam', en: 'Dar es Salaam, Tanzania largest city', ex: 'Dar es Salaam ni jiji kubwa la biashara.' },
    ]
  },
  {
    id: 'wanyama',
    name: 'Wanyama wa Tanzania',
    sub: 'Tanzanian Animals',
    icon: '🦁',
    color: '#66BB6A',
    words: [
      { sw: 'SIMBA', en: 'Lion', ex: 'Simba anaishi mbugani na familia yake.', note: 'Tanzania ina idadi kubwa ya simba duniani.' },
      { sw: 'TEMBO', en: 'Elephant', ex: 'Tembo mkubwa ananywa maji mtoni.', note: 'Serengeti na Mikumi vina tembo wengi.' },
      { sw: 'TWIGA', en: 'Giraffe', ex: 'Twiga anakula majani ya mti mrefu.' },
      { sw: 'NYATI', en: 'Buffalo', ex: 'Nyati ni hatari sana ukimkaribia.' },
      { sw: 'CHUI', en: 'Leopard', ex: 'Chui anapanda mti usiku na nyama yake.' },
      { sw: 'KIFARU', en: 'Rhinoceros', ex: 'Kifaru ni mnyama alio hatarini kutoweka.' },
      { sw: 'PUNDAMILIA', en: 'Zebra', ex: 'Pundamilia wana mistari nyeusi na nyeupe.', note: 'Jina linahusishwa na mistari ya mwilini kama milia.' },
      { sw: 'NYUMBU', en: 'Wildebeest / gnu', ex: 'Nyumbu wengi wanahamia kila mwaka.', note: 'Uhamaji wa nyumbu Serengeti ni maarufu duniani.' },
      { sw: 'FISI', en: 'Hyena', ex: 'Fisi analia usiku na sauti ya ajabu.' },
      { sw: 'NYANI', en: 'Monkey / baboon', ex: 'Nyani anakula matunda msituni.' },
      { sw: 'KIBOKO', en: 'Hippopotamus', ex: 'Kiboko anaishi mtoni na anakula nyasi.' },
      { sw: 'SWALA', en: 'Gazelle / antelope', ex: 'Swala anaruka mbio mbugani.' },
    ]
  },
  {
    id: 'salamu',
    name: 'Salamu na Mazungumzo',
    sub: 'Greetings & Conversation',
    icon: '👋',
    color: '#AB47BC',
    words: [
      { sw: 'HABARI', en: 'News / how are you?', ex: 'Habari za asubuhi? Nzuri!', note: 'Majibu ya kawaida: Nzuri, Safi, Poa.' },
      { sw: 'KARIBU', en: 'Welcome / come in', ex: 'Karibu nyumbani kwangu!', note: 'Unaweza pia kusema "Karibu sana" kwa msisitizo.' },
      { sw: 'ASANTE', en: 'Thank you', ex: 'Asante sana kwa msaada wako.', note: 'Jibu la asante ni "Karibu" au "Sawa".' },
      { sw: 'SAMAHANI', en: 'Sorry / excuse me', ex: 'Samahani, naweza kupita?', note: 'Pia hutumika kusema "Msamaha" rasmi zaidi.' },
      { sw: 'TAFADHALI', en: 'Please', ex: 'Tafadhali nipe maji, nina kiu.' },
      { sw: 'KWAHERI', en: 'Goodbye', ex: 'Kwaheri! Tutaonana kesho.', note: 'Kwa watu wengi unasema "Kwaherini".' },
      { sw: 'NDIYO', en: 'Yes', ex: 'Ndiyo, ninaelewa vizuri.' },
      { sw: 'HAPANA', en: 'No', ex: 'Hapana, sitaki sukari kwenye chai yangu.' },
      { sw: 'SHIKAMOO', en: 'Respectful greeting (to elders)', ex: 'Shikamoo babu! Habari za leo?', note: 'Jibu ni "Marahaba" — heshima muhimu sana Tanzania.' },
      { sw: 'MAMBO', en: 'How\'s things? (informal)', ex: 'Mambo vipi? — Poa kabisa!', note: '"Mambo" ni salamu ya vijana na marafiki.' },
      { sw: 'SAWA', en: 'OK / alright', ex: 'Sawa, nitakuja saa tatu.' },
      { sw: 'POLE', en: 'Sorry (empathy) / slowly', ex: 'Pole sana kwa msiba wako.', note: '"Pole pole" inamaanisha "slowly slowly".' },
    ]
  },
  {
    id: 'familia',
    name: 'Familia',
    sub: 'Family',
    icon: '👨‍👩‍👧‍👦',
    color: '#FFA726',
    words: [
      { sw: 'MAMA', en: 'Mother', ex: 'Mama wangu anapika chakula kitamu.', note: '"Mama" pia ni salamu ya heshima kwa mwanamke mzima.' },
      { sw: 'BABA', en: 'Father', ex: 'Baba ananisaidia na kazi za shule.' },
      { sw: 'DADA', en: 'Sister (older)', ex: 'Dada yangu anaishi Dar es Salaam.' },
      { sw: 'KAKA', en: 'Brother (older)', ex: 'Kaka yangu ni daktari.' },
      { sw: 'MTOTO', en: 'Child', ex: 'Mtoto anacheza kwa furaha.' },
      { sw: 'BABU', en: 'Grandfather', ex: 'Babu ananieleza hadithi za zamani.', note: '"Bibi" ni bibi (grandmother) na "babu" ni babu (grandfather).' },
      { sw: 'BIBI', en: 'Grandmother / older woman', ex: 'Bibi ananitengenezea chai.' },
      { sw: 'MJOMBA', en: 'Uncle (mother\'s brother)', ex: 'Mjomba wangu anaishi Mwanza.' },
      { sw: 'SHANGAZI', en: 'Aunt (father\'s sister)', ex: 'Shangazi ananiletea zawadi sikukuu.' },
      { sw: 'BINAMU', en: 'Cousin', ex: 'Binamu zangu wanakaa Arusha.' },
      { sw: 'MUME', en: 'Husband', ex: 'Mume wake ni mwalimu mzuri.' },
      { sw: 'MKE', en: 'Wife', ex: 'Mke wake anapenda kupika pilau.' },
    ]
  },
  {
    id: 'biashara',
    name: 'Biashara na Sokoni',
    sub: 'Business & Market',
    icon: '🛒',
    color: '#26C6DA',
    words: [
      { sw: 'SOKO', en: 'Market', ex: 'Mama anaenda sokoni kununua mboga.', note: 'Masoko ya Tanzania ni ya rangi na ya kupendeza sana.' },
      { sw: 'DUKA', en: 'Shop / store', ex: 'Duka hili lina vitu vingi.' },
      { sw: 'BEI', en: 'Price', ex: 'Bei ya mchele ni ngapi leo?' },
      { sw: 'PESA', en: 'Money', ex: 'Sina pesa za kutosha kununua hilo.' },
      { sw: 'NUNUA', en: 'To buy', ex: 'Ninataka kununua kanga mbili.' },
      { sw: 'UZA', en: 'To sell', ex: 'Anauza samaki bei nzuri.' },
      { sw: 'BIDHAA', en: 'Goods / products', ex: 'Bidhaa hizi zimetoka China.' },
      { sw: 'FAIDA', en: 'Profit / benefit', ex: 'Biashara yake ina faida kubwa.' },
      { sw: 'MTEJA', en: 'Customer / client', ex: 'Wateja wengi wanakuja asubuhi.' },
      { sw: 'PUNGUZA', en: 'To reduce / discount', ex: 'Tafadhali punguza bei kidogo.' },
      { sw: 'LIPA', en: 'To pay', ex: 'Nimelipa kwa simu ya Mpesa.' },
      { sw: 'HESABU', en: 'Calculation / arithmetic', ex: 'Hesabu yake ni sahihi kabisa.' },
    ]
  },
  {
    id: 'usafiri',
    name: 'Usafiri',
    sub: 'Transport & Travel',
    icon: '🚌',
    color: '#EC407A',
    words: [
      { sw: 'SAFARI', en: 'Journey / trip', ex: 'Tunaenda safari ya Arusha kesho.', note: 'Neno "safari" limetoka Kiswahili hadi lugha za Ulaya!' },
      { sw: 'GARI', en: 'Car / vehicle', ex: 'Gari lake ni jipya na zuri.' },
      { sw: 'BASI', en: 'Bus', ex: 'Napanda basi kwenda mjini kila asubuhi.' },
      { sw: 'DALADALA', en: 'Minibus / shared taxi', ex: 'Daladala ni usafiri wa kawaida Dar es Salaam.', note: 'Daladala zinaitwa hivyo kwa sababu zilikuwa zinagharimu "dollar dollar" zamani.' },
      { sw: 'BODA', en: 'Motorcycle taxi', ex: 'Boda inafika haraka mtaani.' },
      { sw: 'BAJAJI', en: 'Three-wheeled auto-rickshaw', ex: 'Napanda bajaji kwenda stendi.' },
      { sw: 'NDEGE', en: 'Airplane / bird', ex: 'Ndege inaondoka saa mbili usiku.' },
      { sw: 'TRENI', en: 'Train', ex: 'Treni ya TAZARA inakwenda Zambia.' },
      { sw: 'BARABARA', en: 'Road / street', ex: 'Barabara hii imejengwa vizuri.' },
      { sw: 'BANDARI', en: 'Port / harbour', ex: 'Bandari ya Dar es Salaam ni kubwa.' },
      { sw: 'TIKETI', en: 'Ticket', ex: 'Nimenunua tiketi ya basi tayari.' },
      { sw: 'STENDI', en: 'Bus station / stop', ex: 'Nitakungojea stendi ya mabasi.' },
      { sw: 'DEREVA', en: 'Driver', ex: 'Dereva wetu anajua njia vizuri.' },
    ]
  },
  {
    id: 'mazingira',
    name: 'Mazingira na Hali ya Hewa',
    sub: 'Environment & Weather',
    icon: '🌍',
    color: '#8D6E63',
    words: [
      { sw: 'JUA', en: 'Sun / sunshine', ex: 'Jua la Tanzania linawaka sana mchana.' },
      { sw: 'MVUA', en: 'Rain', ex: 'Mvua inanyesha masika yote.' },
      { sw: 'UPEPO', en: 'Wind', ex: 'Upepo wa baharini ni baridi na mzuri.' },
      { sw: 'BAHARI', en: 'Ocean / sea', ex: 'Bahari ya Hindi ipo mashariki mwa Tanzania.' },
      { sw: 'MLIMA', en: 'Mountain', ex: 'Mlima Kilimanjaro ni mrefu zaidi Afrika.', note: 'Kilimanjaro ni mlima mrefu zaidi barani Afrika — 5,895m.' },
      { sw: 'MTO', en: 'River', ex: 'Mto Rufiji ni mrefu zaidi Tanzania.' },
      { sw: 'ZIWA', en: 'Lake', ex: 'Ziwa Victoria ni kubwa zaidi Afrika.' },
      { sw: 'MSITU', en: 'Forest / jungle', ex: 'Msitu wa Udzungwa una miti mingi.' },
      { sw: 'JOTO', en: 'Heat / warmth', ex: 'Joto la pwani ni kali sana Januari.' },
      { sw: 'BARIDI', en: 'Cold / cool', ex: 'Baridi inaingia Julai na Agosti.' },
      { sw: 'PWANI', en: 'Coast / beach', ex: 'Pwani ya Zanzibar ni nzuri sana.' },
      { sw: 'ARDHI', en: 'Land / soil / earth', ex: 'Ardhi ya Tanzania ni nzuri kwa kilimo.' },
    ]
  },
  {
    id: 'utamaduni',
    name: 'Utamaduni wa Tanzania',
    sub: 'Tanzanian Culture',
    icon: '🥁',
    color: '#7E57C2',
    words: [
      { sw: 'NGOMA', en: 'Drum / traditional dance', ex: 'Ngoma zinapigiwa sherehe ya harusi.', note: 'Kuna aina nyingi za ngoma Tanzania, kila kabila lina zake.' },
      { sw: 'KANGA', en: 'Colorful traditional cloth with a saying', ex: 'Mama anabeba mtoto kwa kanga mgongoni.', note: 'Kanga ina methali au ujumbe mfupi katika Kiswahili.' },
      { sw: 'KITENGE', en: 'Colorful wax print fabric', ex: 'Amelishwa nguo nzuri ya kitenge.' },
      { sw: 'TAARAB', en: 'Musical genre mixing Arabic and Swahili', ex: 'Taarab ni muziki maarufu Zanzibar.', note: 'Taarab inachanganya athari za Kiarabu, Kiafrika na Kihindi.' },
      { sw: 'HARUSI', en: 'Wedding', ex: 'Harusi ya jirani ilikuwa na furaha nyingi.' },
      { sw: 'SHEREHE', en: 'Celebration / party', ex: 'Sherehe ya uhuru ni tarehe 9 Desemba.', note: 'Tanzania ilipata uhuru tarehe 9 Desemba 1961.' },
      { sw: 'MILA', en: 'Culture / traditions / customs', ex: 'Mila za Tanzania ni nyingi na tofauti.' },
      { sw: 'HADITHI', en: 'Story / tale', ex: 'Bibi ananieleza hadithi za kimapokeo.', note: 'Hadithi za kimapokeo za Kiswahili zinaanza na "Hadithi hadithi — hadithi njoo!"' },
      { sw: 'SANAA', en: 'Art / craft', ex: 'Sanaa za Tanzania zinauza vizuri kwa watalii.' },
      { sw: 'WIMBO', en: 'Song', ex: 'Wimbo huu wa bongo flava ni mzuri.' },
    ]
  },
  {
    id: 'historia',
    name: 'Historia na Taifa',
    sub: 'History & Nation',
    icon: '🏛️',
    color: '#EF5350',
    words: [
      { sw: 'UHURU', en: 'Freedom / independence', ex: 'Uhuru wa Tanzania ulipatikana 1961.', note: 'Tanganyika ilipata uhuru 9 Desemba 1961. Muungano na Zanzibar ulianza 1964.' },
      { sw: 'AMANI', en: 'Peace', ex: 'Tanzania inajulikana kwa amani na utulivu.' },
      { sw: 'TAIFA', en: 'Nation / country', ex: 'Taifa letu linastawi kila siku.' },
      { sw: 'RAIS', en: 'President', ex: 'Rais wa Tanzania anaishi Ikulu Dar es Salaam.' },
      { sw: 'BENDERA', en: 'Flag', ex: 'Bendera ya Tanzania ina rangi nne.', note: 'Rangi za bendera: kijani, njano, nyeusi, na bluu.' },
      { sw: 'SERIKALI', en: 'Government', ex: 'Serikali inajengea barabara mpya.' },
      { sw: 'KATIBA', en: 'Constitution', ex: 'Katiba ya Tanzania inalinda haki za wananchi.' },
      { sw: 'WANANCHI', en: 'Citizens / the people', ex: 'Wananchi wanaomba maendeleo zaidi.' },
      { sw: 'MUUNGANO', en: 'Union', ex: 'Muungano wa Tanganyika na Zanzibar ni nguvu.', note: 'Muungano ulianzishwa tarehe 26 Aprili 1964.' },
      { sw: 'LUGHA', en: 'Language', ex: 'Lugha ya taifa ya Tanzania ni Kiswahili.' },
    ]
  },
  {
    id: 'kila-siku',
    name: 'Maneno ya Kila Siku',
    sub: 'Everyday Words',
    icon: '🏠',
    color: '#29B6F6',
    words: [
      { sw: 'NYUMBA', en: 'House / home', ex: 'Nyumba yetu iko karibu na shule.' },
      { sw: 'CHUMBA', en: 'Room', ex: 'Chumba changu kina dirisha kubwa.' },
      { sw: 'KITABU', en: 'Book', ex: 'Ninasoma kitabu cha Kiswahili.' },
      { sw: 'KALAMU', en: 'Pen', ex: 'Kalamu yangu iko mezani.' },
      { sw: 'MEZA', en: 'Table', ex: 'Chakula kiko juu ya meza.' },
      { sw: 'KITI', en: 'Chair', ex: 'Kiti hiki ni kizuri.' },
      { sw: 'DIRISHA', en: 'Window', ex: 'Fungua dirisha tupate hewa.' },
      { sw: 'MLANGO', en: 'Door', ex: 'Mlango umefungwa vizuri.' },
      { sw: 'SHULE', en: 'School', ex: 'Watoto wanaenda shule asubuhi.' },
      { sw: 'DAKTARI', en: 'Doctor', ex: 'Daktari anamsaidia mgonjwa.' },
      { sw: 'RANGI', en: 'Color', ex: 'Rangi ya bendera ni nzuri.' },
      { sw: 'NAMBA', en: 'Number', ex: 'Namba yangu ya simu ni mpya.' },
      { sw: 'MKONO', en: 'Hand / arm', ex: 'Ninainua mkono kujibu swali.' },
      { sw: 'MGUU', en: 'Leg / foot', ex: 'Mguu wangu umechoka baada ya safari.' },
      { sw: 'KICHWA', en: 'Head', ex: 'Kichwa changu kinafikiria maneno mapya.' },
      { sw: 'MAJI', en: 'Water', ex: 'Ninakunywa maji kila siku.' },
      { sw: 'RAFIKI', en: 'Friend', ex: 'Rafiki yangu anajifunza Kiswahili.' },
      { sw: 'KAZI', en: 'Work', ex: 'Kazi yangu inaanza saa mbili.' },
      { sw: 'USIKU', en: 'Night', ex: 'Usiku kuna utulivu nyumbani.' },
      { sw: 'ASUBUHI', en: 'Morning', ex: 'Asubuhi tunakunywa chai.' },
      { sw: 'SIMU', en: 'Phone', ex: 'Simu yangu iko mezani.' },
      { sw: 'SAA', en: 'Clock / watch', ex: 'Saa inaonyesha saa mbili.' },
      { sw: 'DAFTARI', en: 'Notebook', ex: 'Ninaandika maneno kwenye daftari.' },
      { sw: 'UFUNGUO', en: 'Key', ex: 'Ufunguo wa nyumba uko mfukoni.' },
      { sw: 'VIATU', en: 'Shoes', ex: 'Viatu vyangu viko karibu na mlango.' },
      { sw: 'NGUO', en: 'Clothes', ex: 'Nguo safi ziko kabatini.' },
      { sw: 'KIKOMBE', en: 'Cup / mug', ex: 'Chai iko kwenye kikombe.' },
      { sw: 'SAHANI', en: 'Plate', ex: 'Wali uko kwenye sahani.' },
      { sw: 'KIJIKO', en: 'Spoon', ex: 'Kijiko kiko pembeni ya sahani.' },
      { sw: 'SABUNI', en: 'Soap', ex: 'Ninaosha mikono kwa sabuni.' },
      { sw: 'TAULO', en: 'Towel', ex: 'Taulo kavu iko bafuni.' },
      { sw: 'TAA', en: 'Lamp / light', ex: 'Washa taa wakati wa usiku.' },
    ]
  },
  {
    id: 'safari-hifadhi',
    name: 'Safari na Hifadhi',
    sub: 'Safari & Parks',
    icon: '🧭',
    color: '#8BC34A',
    words: [
      { sw: 'HIFADHI', en: 'Reserve / protected area', ex: 'Hifadhi inalinda wanyama na mazingira.' },
      { sw: 'MBUGA', en: 'Wildlife park / plains', ex: 'Mbuga ina wanyama wengi.' },
      { sw: 'KAMBI', en: 'Camp', ex: 'Kambi yetu iko karibu na mto.' },
      { sw: 'RAMANI', en: 'Map', ex: 'Ramani inatuonyesha njia ya safari.' },
      { sw: 'MWONGOZA', en: 'Guide', ex: 'Mwongoza anajua njia za mbuga.' },
      { sw: 'PICHA', en: 'Photo / picture', ex: 'Tunapiga picha za mandhari.' },
      { sw: 'DARUBINI', en: 'Binoculars', ex: 'Darubini husaidia kuona ndege mbali.' },
      { sw: 'PORI', en: 'Wilderness / bush', ex: 'Pori lina miti na nyasi nyingi.' },
      { sw: 'MLINZI', en: 'Ranger / guard', ex: 'Mlinzi analinda hifadhi.' },
      { sw: 'KIBALI', en: 'Permit', ex: 'Tunahitaji kibali kuingia hifadhi.' },
      { sw: 'HEWA', en: 'Air / weather', ex: 'Hewa ya mbugani ni safi.' },
      { sw: 'NJIA', en: 'Path / route', ex: 'Njia hii inaelekea kambini.' },
      { sw: 'KAMERA', en: 'Camera', ex: 'Kamera yangu iko tayari kwa picha.' },
      { sw: 'MFUKO', en: 'Bag', ex: 'Mfuko una maji na vitafunwa.' },
      { sw: 'KOFIA', en: 'Hat', ex: 'Kofia inalinda kichwa na jua.' },
      { sw: 'KIVULI', en: 'Shade', ex: 'Tunapumzika chini ya kivuli.' },
      { sw: 'KUNDI', en: 'Group / herd', ex: 'Kundi la swala linakimbia.' },
      { sw: 'ALAMA', en: 'Sign / mark', ex: 'Alama inaonyesha njia salama.' },
      { sw: 'MWENDO', en: 'Pace / movement', ex: 'Mwendo wa gari ni taratibu.' },
      { sw: 'KASKAZINI', en: 'North', ex: 'Tunasafiri kuelekea kaskazini.' },
      { sw: 'WAGENI', en: 'Visitors / guests', ex: 'Wageni wanafika kambini jioni.' },
      { sw: 'TENTI', en: 'Tent', ex: 'Tenti yetu iko karibu na mto.' },
      { sw: 'MALAZI', en: 'Accommodation', ex: 'Malazi yetu yako karibu na hifadhi.' },
      { sw: 'MANDHARI', en: 'Scenery / view', ex: 'Mandhari ya hifadhi ni nzuri sana.' },
      { sw: 'TOCHI', en: 'Flashlight', ex: 'Tochi husaidia kutembea usiku.' },
      { sw: 'CHUPA', en: 'Bottle', ex: 'Chupa ya maji iko kwenye mfuko.' },
      { sw: 'USALAMA', en: 'Safety', ex: 'Usalama wa wageni ni muhimu hifadhini.' },
      { sw: 'TAHADHARI', en: 'Caution / care', ex: 'Mwongoza anatupa tahadhari njiani.' },
      { sw: 'KILELE', en: 'Peak / summit', ex: 'Kilele cha mlima kinaonekana mbali.' },
      { sw: 'KUTEMBEA', en: 'To walk', ex: 'Tunapenda kutembea kwenye njia salama.' },
      { sw: 'KUTAZAMA', en: 'To watch / look at', ex: 'Tunasimama kutazama twiga.' },
      { sw: 'KUPUMZIKA', en: 'To rest', ex: 'Tunakaa kivulini kupumzika.' },
    ]
  },
  {
    id: 'vitendo',
    name: 'Vitendo na Vitenzi',
    sub: 'Verbs & Actions',
    icon: '🎯',
    color: '#5C6BC0',
    words: [
      { sw: 'ANZA', en: 'Start / begin', ex: 'Anza fumbo lako sasa.' },
      { sw: 'ISHA', en: 'Finish / end', ex: 'Tunaisha kazi kabla ya jioni.' },
      { sw: 'JIFUNZE', en: 'Learn', ex: 'Jifunze neno moja jipya kila siku.' },
      { sw: 'SOMA', en: 'Read / study', ex: 'Soma sentensi hii kwa sauti.' },
      { sw: 'ANDIKA', en: 'Write', ex: 'Andika neno hili kwenye daftari.' },
      { sw: 'SIKILIZA', en: 'Listen', ex: 'Sikiliza matamshi kwa makini.' },
      { sw: 'ONA', en: 'See', ex: 'Ninaona twiga mbali.' },
      { sw: 'SEMA', en: 'Say / speak', ex: 'Sema habari kwa rafiki yako.' },
      { sw: 'ULIZA', en: 'Ask', ex: 'Uliza swali ukihitaji msaada.' },
      { sw: 'JIBU', en: 'Answer', ex: 'Jibu swali kwa Kiswahili.' },
      { sw: 'CHEZA', en: 'Play', ex: 'Cheza fumbo na ujifunze.' },
      { sw: 'FANYA', en: 'Do / make', ex: 'Fanya mazoezi kila siku.' },
      { sw: 'PIKA', en: 'Cook', ex: 'Pika wali na maharage leo.' },
      { sw: 'TEMBEA', en: 'Walk / travel', ex: 'Tembea polepole kwenye njia.' },
      { sw: 'LALA', en: 'Sleep', ex: 'Lala mapema baada ya kusoma.' },
      { sw: 'AMKA', en: 'Wake up', ex: 'Amka asubuhi kwa furaha.' },
      { sw: 'FUNGUA', en: 'Open', ex: 'Fungua kitabu chako sasa.' },
      { sw: 'FUNGA', en: 'Close / shut', ex: 'Funga mlango kabla ya kuondoka.' },
      { sw: 'TAFUTA', en: 'Look for / search', ex: 'Tafuta maneno kwenye gridi.' },
      { sw: 'SAIDIA', en: 'Help', ex: 'Saidia rafiki yako kujifunza.' },
      { sw: 'NGOJA', en: 'Wait', ex: 'Ngoja kidogo, basi linakuja.' },
      { sw: 'KAA', en: 'Sit / stay', ex: 'Kaa karibu na dirisha.' },
      { sw: 'TOKA', en: 'Leave / come from', ex: 'Toka nyumbani mapema.' },
      { sw: 'RUDI', en: 'Return / go back', ex: 'Rudi kesho kwa fumbo jipya.' },
    ]
  },
  {
    id: 'muda-ratiba',
    name: 'Muda na Ratiba',
    sub: 'Time & Routines',
    icon: '🕒',
    color: '#00897B',
    words: [
      { sw: 'LEO', en: 'Today', ex: 'Leo tunajifunza maneno mapya.' },
      { sw: 'KESHO', en: 'Tomorrow', ex: 'Kesho tutacheza fumbo jingine.' },
      { sw: 'JANA', en: 'Yesterday', ex: 'Jana nilisoma Kiswahili.' },
      { sw: 'DAKIKA', en: 'Minute', ex: 'Subiri dakika moja tafadhali.' },
      { sw: 'WIKI', en: 'Week', ex: 'Wiki hii nina lengo la kujifunza.' },
      { sw: 'MCHANA', en: 'Afternoon / daytime', ex: 'Mchana jua linawaka sana.' },
      { sw: 'JIONI', en: 'Evening', ex: 'Jioni tunakaa na familia.' },
      { sw: 'MAPEMA', en: 'Early', ex: 'Ninaamka mapema kila siku.' },
      { sw: 'BAADAYE', en: 'Later', ex: 'Tutazungumza baadaye.' },
      { sw: 'SASA', en: 'Now', ex: 'Sasa tuanze kujifunza.' },
      { sw: 'MARA', en: 'Time / occasion', ex: 'Mara nyingi nasoma asubuhi.' },
      { sw: 'KILA', en: 'Every / each', ex: 'Kila siku ni nafasi mpya.' },
      { sw: 'MWISHO', en: 'End / finish', ex: 'Mwisho wa wiki tunapumzika.' },
      { sw: 'HARAKA', en: 'Quickly', ex: 'Tembea haraka lakini kwa makini.' },
      { sw: 'DAIMA', en: 'Always', ex: 'Daima kumbuka kusoma maneno mapya.' },
      { sw: 'KARIBUNI', en: 'Soon / nearby', ex: 'Basi litafika karibuni.' },
      { sw: 'JANUARI', en: 'January', ex: 'Januari ni mwanzo wa mwaka.' },
      { sw: 'JUMATATU', en: 'Monday', ex: 'Jumatatu ninaanza kazi mapema.' },
      { sw: 'JUMAMOSI', en: 'Saturday', ex: 'Jumamosi tunaenda sokoni.' },
      { sw: 'KALENDA', en: 'Calendar', ex: 'Tarehe ipo kwenye kalenda.' },
      { sw: 'MIADI', en: 'Appointment', ex: 'Nina miadi na daktari kesho.' },
      { sw: 'MZUNGUKO', en: 'Cycle / routine', ex: 'Mzunguko wa siku huanza asubuhi.' },
      { sw: 'LIKIZO', en: 'Holiday / break', ex: 'Likizo inaanza mwezi ujao.' },
      { sw: 'MAPUMZIKO', en: 'Rest / holiday', ex: 'Mapumziko mafupi yanarudisha nguvu.' },
    ]
  }
];

// Daily puzzle seed words
const DAILY_WORDS = [
  { sw: 'KILIMANJARO', en: 'Highest mountain in Africa', ex: 'Kilimanjaro ni mlima mrefu zaidi Afrika.', note: 'Urefu wake ni mita 5,895.' },
  { sw: 'SERENGETI', en: 'Famous national park in Tanzania', ex: 'Serengeti inajulikana duniani kote.', note: 'Serengeti ina wanyama wengi na mazingira mazuri.' },
  { sw: 'SWAHILI', en: 'The Swahili language', ex: 'Ninajifunza Kiswahili kwa furaha.' },
  { sw: 'BONGO', en: 'Tanzania (slang)', ex: 'Ninapenda kuishi bongo nchi yangu.', note: '"Bongo" ni jina la kimombo la Tanzania linalotumika katika muziki wa bongo flava.' },
  { sw: 'UJAMAA', en: 'African socialism / unity', ex: 'Ujamaa ulianzishwa na Mwalimu Nyerere.', note: 'Ujamaa ulikuwa sera ya Tanzania baada ya uhuru.' },
  { sw: 'NGORONGORO', en: 'Famous conservation area in Tanzania', ex: 'Ngorongoro ina mandhari ya ajabu.', note: 'Ngorongoro ni eneo maarufu kwa wanyama na historia.' },
  { sw: 'MIKUMI', en: 'National park in Tanzania', ex: 'Mikumi iko karibu na Morogoro.' },
  { sw: 'RUAHA', en: 'Large national park in southern Tanzania', ex: 'Ruaha ina wanyama wengi na mito mizuri.' },
  { sw: 'MANYARA', en: 'Lake and national park region', ex: 'Manyara ina ziwa na mazingira mazuri.' },
  { sw: 'TARANGIRE', en: 'National park known for elephants', ex: 'Tarangire ina tembo wengi.' },
  { sw: 'PEMBA', en: 'Island in the Zanzibar archipelago', ex: 'Pemba ina mashamba ya karafuu.' },
  { sw: 'MAFIA', en: 'Island off the Tanzanian coast', ex: 'Mafia ni kisiwa chenye bahari nzuri.' },
  { sw: 'RUKWA', en: 'Region and lake in western Tanzania', ex: 'Rukwa iko magharibi mwa Tanzania.' },
  { sw: 'RUVUMA', en: 'River and region in southern Tanzania', ex: 'Ruvuma inapakana na Msumbiji.' },
  { sw: 'KARATU', en: 'Town near northern safari routes', ex: 'Karatu iko karibu na Ngorongoro.' },
  { sw: 'KILWA', en: 'Historic coastal area', ex: 'Kilwa ina historia ndefu ya pwani.' },
  { sw: 'PANGANI', en: 'Coastal town in Tanga Region', ex: 'Pangani iko karibu na Bahari ya Hindi.' },
  { sw: 'GEITA', en: 'Region near Lake Victoria', ex: 'Geita iko kanda ya ziwa.' },
  { sw: 'SINGIDA', en: 'Region in central Tanzania', ex: 'Singida ina hali ya ukame kiasi.' },
  { sw: 'NJOMBE', en: 'Southern Highlands region', ex: 'Njombe ina baridi na mashamba mengi.' },
  { sw: 'KATAVI', en: 'Remote national park in western Tanzania', ex: 'Katavi ina mazingira tulivu ya mbuga.' },
  { sw: 'MAASAI', en: 'Pastoralist community in East Africa', ex: 'Maasai wana utamaduni unaojulikana sana.' },
  { sw: 'SUKUMA', en: 'Large ethnic community in Tanzania', ex: 'Sukuma ni jamii kubwa nchini Tanzania.' },
  { sw: 'NYERERE', en: 'Name linked to Tanzania first president', ex: 'Nyerere anakumbukwa kwa uongozi wake.', note: 'Mwalimu Julius Nyerere alikuwa rais wa kwanza wa Tanzania.' },
  { sw: 'TAZARA', en: 'Tanzania Zambia railway', ex: 'TAZARA inaunganisha Tanzania na Zambia.' },
  { sw: 'KARAFUU', en: 'Cloves', ex: 'Karafuu ni kiungo maarufu Zanzibar.' },
  { sw: 'KOROSHO', en: 'Cashew nuts', ex: 'Korosho hulimwa sana kusini mwa Tanzania.' },
  { sw: 'TANZANITE', en: 'Blue gemstone from Tanzania', ex: 'Tanzanite hupatikana Tanzania.' },
  { sw: 'KISWAHILI', en: 'Swahili language', ex: 'Kiswahili ni lugha ya taifa.', note: 'Kiswahili huzungumzwa sana Afrika Mashariki.' },
  { sw: 'MWALIMU', en: 'Teacher', ex: 'Mwalimu anafundisha kwa upendo.' },
];

// Word of the day list
const WODS = [
  { word: 'Karibu', meaning: 'Welcome — "Karibu Tanzania!"' },
  { word: 'Ujamaa', meaning: 'Unity/Socialism — "Ujamaa ni nguvu yetu."' },
  { word: 'Poa', meaning: 'Cool/Great — "Mambo? — Poa kabisa!"' },
  { word: 'Asante', meaning: 'Thank you — "Asante sana!"' },
      { word: 'Polepole', meaning: 'Slowly/calmly — "Twende polepole."' },
  { word: 'Subira', meaning: 'Patience — "Subira huvuta heri."' },
  { word: 'Upole', meaning: 'Gentleness — "Upole ni nguvu ya mtu mzima."' },
  { word: 'Safari', meaning: 'Journey — "Safari ndefu huanza hatua moja."' },
  { word: 'Umoja', meaning: 'Unity — "Umoja ni nguvu, utengano ni udhaifu."' },
  { word: 'Pamoja', meaning: 'Together — "Pamoja tutafika mbali."' },
  { word: 'Amani', meaning: 'Peace - "Amani ni zawadi kubwa."' },
  { word: 'Furaha', meaning: 'Joy - "Furaha huanza moyoni."' },
  { word: 'Bidii', meaning: 'Effort - "Bidii huleta mafanikio."' },
  { word: 'Heshima', meaning: 'Respect - "Heshima hujenga jamii."' },
  { word: 'Rafiki', meaning: 'Friend - "Rafiki mwema ni hazina."' },
  { word: 'Nyumbani', meaning: 'At home - "Nyumbani kuna upendo."' },
  { word: 'Leo', meaning: 'Today - "Leo tutajifunza neno jipya."' },
  { word: 'Kesho', meaning: 'Tomorrow - "Kesho ni siku mpya."' },
  { word: 'Sasa', meaning: 'Now - "Sasa tuanze mchezo."' },
  { word: 'Haraka', meaning: 'Quickly - "Tembea haraka lakini kwa makini."' },
  { word: 'Pole', meaning: 'Sorry / gently - "Pole kwa uchovu."' },
  { word: 'Nguvu', meaning: 'Strength - "Nguvu ya kujifunza hukua kila siku."' },
  { word: 'Moyo', meaning: 'Heart - "Moyo wa kujifunza ni muhimu."' },
  { word: 'Ndoto', meaning: 'Dream - "Ndoto kubwa huanza na hatua ndogo."' },
  { word: 'Elimu', meaning: 'Education - "Elimu ni mwanga."' },
  { word: 'Maarifa', meaning: 'Knowledge - "Maarifa huongeza uwezo."' },
  { word: 'Hekima', meaning: 'Wisdom - "Hekima hutusaidia kuchagua vizuri."' },
  { word: 'Tabasamu', meaning: 'Smile - "Tabasamu huleta ukaribu."' },
  { word: 'Shule', meaning: 'School - "Shule ni mahali pa kujifunza."' },
  { word: 'Kitabu', meaning: 'Book - "Kitabu kizuri hufungua dunia."' },
  { word: 'Mwalimu', meaning: 'Teacher - "Mwalimu hutusaidia kuelewa."' },
  { word: 'Mwanafunzi', meaning: 'Student - "Mwanafunzi anauliza swali."' },
  { word: 'Soko', meaning: 'Market - "Soko lina watu wengi."' },
  { word: 'Chai', meaning: 'Tea - "Chai ya asubuhi inanipa nguvu."' },
  { word: 'Nafasi', meaning: 'Chance / space - "Kila siku ni nafasi mpya."' },
  { word: 'Bahati', meaning: 'Luck - "Bahati huambatana na maandalizi."' },
  { word: 'Muda', meaning: 'Time - "Tumia muda kujifunza."' },
  { word: 'Sauti', meaning: 'Voice / sound - "Sauti ya Kiswahili ni nzuri."' },
  { word: 'Mwanga', meaning: 'Light - "Mwanga unaonyesha njia."' },
  { word: 'Njia', meaning: 'Road / way - "Njia ya elimu ni ndefu."' },
  { word: 'Lengo', meaning: 'Goal - "Lengo la leo ni neno moja jipya."' },
  { word: 'Zawadi', meaning: 'Gift - "Kujifunza ni zawadi."' },
  { word: 'Mchezo', meaning: 'Game - "Mchezo huu unafundisha maneno."' },
  { word: 'Ushindi', meaning: 'Victory - "Ushindi huja baada ya mazoezi."' },
  { word: 'Mazoezi', meaning: 'Practice - "Mazoezi hufanya neno likae kichwani."' },
];

const ENCOURAGEMENTS = [
  'Hongera! 🎉', 'Umefanikiwa! 🏆', 'Vizuri sana! ⭐',
  'Nzuri kabisa! 🌟', 'Bora sana! 💪', 'Poa kabisa! 🔥',
  'Endelea hivyo! 👍', 'Wewe ni bingwa! 🦁',
];

const EXTRA_WORDS = {
  chakula: [
    { sw: 'MBOGA', en: 'Vegetables', ex: 'Mboga zinafaa kwa afya.' },
    { sw: 'KARANGA', en: 'Groundnuts / peanuts', ex: 'Karanga huliwa kama kitafunwa.' },
    { sw: 'VITUMBUA', en: 'Rice cakes', ex: 'Vitumbua ni vitamu na chai.' },
    { sw: 'CHAI', en: 'Tea', ex: 'Chai hunywewa asubuhi na mandazi.' },
    { sw: 'SUKARI', en: 'Sugar', ex: 'Ninaweka sukari kidogo kwenye chai.' },
    { sw: 'MKATE', en: 'Bread', ex: 'Mkate ni mzuri kwa kifungua kinywa.' },
    { sw: 'MATUNDA', en: 'Fruit', ex: 'Matunda yapo mezani baada ya chakula.' },
    { sw: 'NYANYA', en: 'Tomato', ex: 'Nyanya nyekundu ziko kwenye kachumbari.' },
    { sw: 'KITUNGUU', en: 'Onion', ex: 'Kitunguu kinaongeza ladha ya chakula.' },
    { sw: 'LIMAU', en: 'Lemon / lime', ex: 'Ninaweka limau kwenye samaki.' },
    { sw: 'MAYAI', en: 'Eggs', ex: 'Mayai mawili yapo kwenye sahani.' },
    { sw: 'MCHUZI', en: 'Sauce / gravy', ex: 'Mchuzi wa maharage una ladha nzuri.' },
  ],
  miji: [
    { sw: 'IRINGA', en: 'City in the Southern Highlands', ex: 'Iringa ina hali ya hewa nzuri.' },
    { sw: 'LINDI', en: 'Coastal town in southern Tanzania', ex: 'Lindi iko kusini mwa Tanzania.' },
    { sw: 'TABORA', en: 'Historic inland town', ex: 'Tabora ina historia ndefu ya biashara.' },
    { sw: 'BUKOBA', en: 'Town near Lake Victoria', ex: 'Bukoba iko kando ya Ziwa Victoria.' },
    { sw: 'KAHAMA', en: 'Town in Shinyanga Region', ex: 'Kahama ni mji wenye shughuli nyingi.' },
    { sw: 'MUSOMA', en: 'Town on Lake Victoria', ex: 'Musoma ina mandhari nzuri ya ziwa.' },
    { sw: 'SHINYANGA', en: 'Region and town in northern Tanzania', ex: 'Shinyanga iko kanda ya ziwa.' },
    { sw: 'MAFINGA', en: 'Town in Iringa Region', ex: 'Mafinga ina hali ya baridi.' },
    { sw: 'KIJIJI', en: 'Village', ex: 'Kijiji chetu kina soko kila Jumamosi.' },
    { sw: 'KITONGOJI', en: 'Neighbourhood / small settlement', ex: 'Kitongoji hiki kiko karibu na barabara.' },
    { sw: 'MITAA', en: 'Streets / neighbourhoods', ex: 'Mitaa ya mjini ina watu wengi.' },
    { sw: 'KUSINI', en: 'South', ex: 'Lindi iko kusini mwa Tanzania.' },
    { sw: 'MASHARIKI', en: 'East', ex: 'Bahari ipo mashariki mwa Tanzania.' },
    { sw: 'MAGHARIBI', en: 'West', ex: 'Kigoma iko magharibi mwa Tanzania.' },
  ],
  wanyama: [
    { sw: 'TAUSI', en: 'Peacock', ex: 'Tausi ana manyoya mazuri.' },
    { sw: 'KOBE', en: 'Tortoise', ex: 'Kobe hutembea polepole.' },
    { sw: 'MAMBA', en: 'Crocodile', ex: 'Mamba anaishi majini.' },
    { sw: 'MBWA', en: 'Dog', ex: 'Mbwa analinda nyumba usiku.' },
    { sw: 'PAKA', en: 'Cat', ex: 'Paka anakunywa maziwa.' },
    { sw: 'KONDOO', en: 'Sheep', ex: 'Kondoo wanakula majani shambani.' },
    { sw: 'DUMA', en: 'Cheetah', ex: 'Duma anakimbia kwa kasi sana mbugani.' },
    { sw: 'MBUNI', en: 'Ostrich', ex: 'Mbuni ana miguu mirefu na hukimbia haraka.' },
    { sw: 'KINYONGA', en: 'Chameleon', ex: 'Kinyonga anatembea polepole kwenye tawi.' },
    { sw: 'NYOKA', en: 'Snake', ex: 'Nyoka anaonekana karibu na mawe.' },
    { sw: 'SUNGURA', en: 'Rabbit', ex: 'Sungura anakula majani shambani.' },
    { sw: 'KIPEPEO', en: 'Butterfly', ex: 'Kipepeo anaruka juu ya maua.' },
  ],
  salamu: [
    { sw: 'MARAHABA', en: 'Respectful reply to Shikamoo', ex: 'Bibi anajibu, Marahaba.' },
    { sw: 'SAFI', en: 'Fine / clean / good', ex: 'Habari? Safi kabisa.' },
    { sw: 'TUTAONANA', en: 'See you', ex: 'Tutaonana kesho asubuhi.' },
    { sw: 'HODI', en: 'May I come in?', ex: 'Mgeni anasema hodi mlangoni.' },
    { sw: 'JAMBO', en: 'Hello', ex: 'Jambo rafiki yangu.' },
    { sw: 'SALAMA', en: 'Safe / peaceful', ex: 'Umefika salama nyumbani?' },
    { sw: 'HONGERA', en: 'Congratulations', ex: 'Hongera kwa kumaliza fumbo lako.' },
    { sw: 'NAOMBA', en: 'I request / please', ex: 'Naomba unisaidie kidogo.' },
    { sw: 'NAHITAJI', en: 'I need', ex: 'Nahitaji maji tafadhali.' },
    { sw: 'NAFURAHI', en: 'I am happy', ex: 'Nafurahi kukuona leo.' },
    { sw: 'TAYARI', en: 'Ready / already', ex: 'Niko tayari kuanza safari.' },
    { sw: 'SITAKI', en: 'I do not want', ex: 'Sitaki sukari kwenye chai.' },
  ],
  familia: [
    { sw: 'SHEMEJI', en: 'In-law', ex: 'Shemeji yangu ametutembelea.' },
    { sw: 'MPWA', en: 'Niece / nephew', ex: 'Mpwa wangu anasoma shule.' },
    { sw: 'FAMILIA', en: 'Family', ex: 'Familia yetu inaishi Mwanza.' },
    { sw: 'NDUGU', en: 'Relative / sibling', ex: 'Ndugu zangu wanaishi karibu.' },
    { sw: 'MJUKUU', en: 'Grandchild', ex: 'Bibi anacheza na mjukuu wake.' },
    { sw: 'MZAZI', en: 'Parent', ex: 'Mzazi anampeleka mtoto shule.' },
    { sw: 'WATOTO', en: 'Children', ex: 'Watoto wanacheza uwanjani jioni.' },
    { sw: 'WAZEE', en: 'Elders', ex: 'Wazee wanashiriki hadithi za zamani.' },
    { sw: 'WALEZI', en: 'Guardians / caregivers', ex: 'Walezi wanawasaidia watoto kusoma.' },
    { sw: 'MDOGO', en: 'Younger sibling / younger person', ex: 'Mdogo wangu anapenda kusoma.' },
    { sw: 'MAPACHA', en: 'Twins', ex: 'Mapacha hao wanafanana sana.' },
    { sw: 'JIRANI', en: 'Neighbour', ex: 'Jirani yetu ametusalimia asubuhi.' },
  ],
  biashara: [
    { sw: 'RISITI', en: 'Receipt', ex: 'Nipe risiti baada ya kulipa.' },
    { sw: 'CHENJI', en: 'Change / balance', ex: 'Muuzaji amenirudishia chenji.' },
    { sw: 'KIPIMO', en: 'Measure / scale', ex: 'Kipimo kinaonyesha kilo moja.' },
    { sw: 'GHARAMA', en: 'Cost / expense', ex: 'Gharama ya safari imepanda.' },
    { sw: 'AKIBA', en: 'Savings', ex: 'Anaweka akiba kila mwezi.' },
    { sw: 'REJAREJA', en: 'Retail', ex: 'Duka hili linauza bidhaa rejareja.' },
    { sw: 'MALIPO', en: 'Payment', ex: 'Malipo yanafanyika kwa simu au pesa taslimu.' },
    { sw: 'MAPATO', en: 'Income / revenue', ex: 'Mapato ya duka yanaongezeka kila mwezi.' },
    { sw: 'MKOPO', en: 'Loan', ex: 'Anaomba mkopo wa kuanza biashara.' },
    { sw: 'MKATABA', en: 'Contract / agreement', ex: 'Wamesaini mkataba wa biashara.' },
    { sw: 'HUDUMA', en: 'Service', ex: 'Huduma nzuri huwafanya wateja warudi.' },
    { sw: 'OFA', en: 'Offer / deal', ex: 'Duka lina ofa nzuri wiki hii.' },
  ],
  usafiri: [
    { sw: 'ABIRIA', en: 'Passenger', ex: 'Abiria wanasubiri basi.' },
    { sw: 'KITUO', en: 'Station / stop', ex: 'Kituo cha daladala kiko karibu.' },
    { sw: 'NAULI', en: 'Fare', ex: 'Nauli ya basi imeongezeka.' },
    { sw: 'TEKSI', en: 'Taxi', ex: 'Teksi inanisubiri nje ya hoteli.' },
    { sw: 'MELI', en: 'Ship / ferry boat', ex: 'Meli inaelekea Zanzibar.' },
    { sw: 'LORI', en: 'Truck', ex: 'Lori linabeba mizigo barabarani.' },
    { sw: 'STESHENI', en: 'Station', ex: 'Tunakutana stesheni kabla ya safari.' },
    { sw: 'RELI', en: 'Railway', ex: 'Reli inaunganisha miji mingi.' },
    { sw: 'MWELEKEO', en: 'Direction', ex: 'Mwongoza anaonyesha mwelekeo wa stendi.' },
    { sw: 'KUPANDA', en: 'To board / get on', ex: 'Abiria wanapanda basi mapema.' },
    { sw: 'KUSHUKA', en: 'To get off / descend', ex: 'Tunashuka kituo kinachofuata.' },
  ],
  mazingira: [
    { sw: 'MAWINGU', en: 'Clouds', ex: 'Mawingu yamefunika jua.' },
    { sw: 'KISIWA', en: 'Island', ex: 'Kisiwa cha Zanzibar ni maarufu.' },
    { sw: 'BONDE', en: 'Valley', ex: 'Bonde lina miti mingi.' },
    { sw: 'NYASI', en: 'Grass', ex: 'Nyasi zimeota baada ya mvua.' },
    { sw: 'UDONGO', en: 'Soil', ex: 'Udongo mzuri husaidia mimea kukua.' },
    { sw: 'THELUJI', en: 'Snow', ex: 'Theluji ipo juu ya Kilimanjaro.' },
    { sw: 'MWEZI', en: 'Moon / month', ex: 'Mwezi unaangaza usiku wa leo.' },
    { sw: 'ANGA', en: 'Sky', ex: 'Anga ni safi baada ya mvua.' },
    { sw: 'NYOTA', en: 'Star', ex: 'Nyota nyingi zinaonekana usiku.' },
    { sw: 'MIMEA', en: 'Plants', ex: 'Mimea inahitaji maji na jua.' },
    { sw: 'MAUA', en: 'Flowers', ex: 'Maua yanachanua baada ya mvua.' },
    { sw: 'UKAME', en: 'Drought', ex: 'Ukame huathiri kilimo katika baadhi ya maeneo.' },
  ],
  utamaduni: [
    { sw: 'METHALI', en: 'Proverb', ex: 'Methali hufundisha hekima.' },
    { sw: 'JANDO', en: 'Traditional initiation', ex: 'Jando ni sehemu ya mila katika jamii fulani.' },
    { sw: 'MAPISHI', en: 'Cooking / cuisine', ex: 'Mapishi ya Tanzania ni tofauti.' },
    { sw: 'DESTURI', en: 'Custom', ex: 'Desturi nzuri hujenga heshima.' },
    { sw: 'SHUJAA', en: 'Hero', ex: 'Shujaa anakumbukwa kwa matendo mema.' },
    { sw: 'KWAYA', en: 'Choir', ex: 'Kwaya inaimba kanisani.' },
    { sw: 'MICHEZO', en: 'Sports / games', ex: 'Michezo huleta watu pamoja.' },
    { sw: 'BONGOFLAVA', en: 'Tanzanian popular music style', ex: 'Bongo flava inapendwa na vijana wengi.' },
    { sw: 'MZIKI', en: 'Music', ex: 'Muziki wa taarab unasikika Zanzibar.' },
    { sw: 'UFUNDI', en: 'Craftsmanship / skill', ex: 'Ufundi wa kutengeneza vinyago unathaminiwa.' },
    { sw: 'MAPAMBO', en: 'Decorations', ex: 'Mapambo yanapendeza kwenye sherehe.' },
    { sw: 'MAONYESHO', en: 'Exhibition / show', ex: 'Maonyesho ya sanaa yanafanyika mjini.' },
    { sw: 'JUMUIYA', en: 'Community', ex: 'Jumuiya huleta watu pamoja.' },
    { sw: 'MAVAZI', en: 'Attire / clothing', ex: 'Mavazi ya sherehe yana rangi nyingi.' },
  ],
  historia: [
    { sw: 'IKULU', en: 'State House', ex: 'Ikulu ni ofisi muhimu ya nchi.' },
    { sw: 'BUNGE', en: 'Parliament', ex: 'Bunge hukutana Dodoma.' },
    { sw: 'KURA', en: 'Vote', ex: 'Wananchi wanapiga kura.' },
    { sw: 'SHERIA', en: 'Law', ex: 'Sheria inalinda haki za watu.' },
    { sw: 'WAZIRI', en: 'Minister', ex: 'Waziri ametangaza mpango mpya.' },
    { sw: 'BALOZI', en: 'Ambassador', ex: 'Balozi anawakilisha nchi yake.' },
    { sw: 'WILAYA', en: 'District', ex: 'Wilaya ina ofisi za serikali.' },
    { sw: 'MKOA', en: 'Region', ex: 'Kila mkoa una viongozi wake.' },
    { sw: 'JAMHURI', en: 'Republic', ex: 'Tanzania ni jamhuri yenye historia ndefu.' },
    { sw: 'TAREHE', en: 'Date', ex: 'Tarehe ya sherehe imeandikwa kwenye kalenda.' },
    { sw: 'MWAKA', en: 'Year', ex: 'Mwaka huu tunajifunza maneno mengi.' },
    { sw: 'KUMBUKUMBU', en: 'Memory / record', ex: 'Picha ni kumbukumbu ya safari nzuri.' },
    { sw: 'MAENDELEO', en: 'Development / progress', ex: 'Maendeleo hujengwa kwa ushirikiano.' },
    { sw: 'MIPAKA', en: 'Borders / boundaries', ex: 'Mto huu uko karibu na mipaka ya nchi.' },
  ],
};

const ADVANCED_WORDS = {
  chakula: [
    { sw: 'MIHOGO', en: 'Cassava', ex: 'Mihogo huliwa kwa chai au nazi.' },
    { sw: 'VIAZI', en: 'Potatoes', ex: 'Viazi vya kukaanga vinapendwa sana.' },
  ],
  miji: [
    { sw: 'BAGAMOYO', en: 'Historic coastal town', ex: 'Bagamoyo ina historia ya pwani.' },
    { sw: 'SONGEA', en: 'Town in southern Tanzania', ex: 'Songea iko kusini mwa Tanzania.' },
  ],
  wanyama: [
    { sw: 'CHURA', en: 'Frog', ex: 'Chura husikika wakati wa mvua.' },
    { sw: 'KIMA', en: 'Small monkey', ex: 'Kima anakaa kwenye miti.' },
  ],
  salamu: [
    { sw: 'SHUKRANI', en: 'Thanks / gratitude', ex: 'Shukrani kwa msaada wako.' },
    { sw: 'NASHUKURU', en: 'I am thankful', ex: 'Nashukuru kwa chakula.' },
  ],
  familia: [
    { sw: 'WAZAZI', en: 'Parents', ex: 'Wazazi wangu wanaishi Dodoma.' },
    { sw: 'WAJUKUU', en: 'Grandchildren', ex: 'Bibi anawapenda wajukuu wake.' },
  ],
  biashara: [
    { sw: 'MTAJI', en: 'Capital for business', ex: 'Anahitaji mtaji kuanza biashara.' },
    { sw: 'MNADA', en: 'Auction / market day', ex: 'Mnada unafanyika Jumamosi.' },
  ],
  usafiri: [
    { sw: 'UWANJA', en: 'Airport / field', ex: 'Uwanja wa ndege uko karibu.' },
    { sw: 'KIVUKO', en: 'Ferry', ex: 'Kivuko kinabeba abiria.' },
  ],
  mazingira: [
    { sw: 'MAPOROMOKO', en: 'Waterfalls', ex: 'Maporomoko ya maji ni mazuri.' },
    { sw: 'NYANDA', en: 'Grasslands / plains', ex: 'Nyanda zina majani mengi.' },
  ],
  utamaduni: [
    { sw: 'USHAIRI', en: 'Poetry', ex: 'Ushairi wa Kiswahili una mizani.' },
    { sw: 'VYOMBO', en: 'Utensils / instruments', ex: 'Vyombo vya ngoma vinapigwa.' },
  ],
  historia: [
    { sw: 'AZIMIO', en: 'Declaration', ex: 'Azimio ni tamko muhimu.' },
    { sw: 'URITHI', en: 'Heritage', ex: 'Urithi wa taifa unalindwa.' },
  ],
};

const BADGE_DEFS = [
  { id: 'first-puzzle', icon: '🏆', sw: 'Fumbo la Kwanza', en: 'First Puzzle', descSw: 'Kamilisha fumbo lako la kwanza.', descEn: 'Complete your first puzzle.' },
  { id: 'words-10', icon: '📚', sw: 'Maneno 10', en: '10 Words', descSw: 'Pata maneno 10.', descEn: 'Find 10 words.' },
  { id: 'words-50', icon: '📖', sw: 'Maneno 50', en: '50 Words', descSw: 'Pata maneno 50 kwenye mafumbo.', descEn: 'Find 50 words across puzzles.' },
  { id: 'daily-3', icon: '☀️', sw: 'Siku 3', en: '3 Day Streak', descSw: 'Kamilisha fumbo la leo siku 3.', descEn: 'Complete daily puzzles for 3 days.' },
  { id: 'daily-7', icon: '🔥', sw: 'Wiki ya Safari', en: '7 Day Streak', descSw: 'Fikisha streak ya siku 7.', descEn: 'Reach a 7 day streak.' },
  { id: 'three-star', icon: '⭐', sw: 'Nyota Tatu', en: 'Three Star', descSw: 'Pata nyota 3 kwenye mada yoyote.', descEn: 'Earn 3 stars in any category.' },
  { id: 'saved-5', icon: '🔖', sw: 'Mkusanyaji', en: 'Collector', descSw: 'Hifadhi maneno 5 kwa marudio.', descEn: 'Save 5 words for revision.' },
  { id: 'daily-goal', icon: '🎯', sw: 'Lengo la Leo', en: 'Daily Goal', descSw: 'Dai zawadi ya lengo la siku.', descEn: 'Claim a daily goal reward.' },
  { id: 'weekly-challenge', icon: '🧭', sw: 'Changamoto ya Wiki', en: 'Weekly Challenge', descSw: 'Kamilisha changamoto ya wiki.', descEn: 'Complete a weekly challenge.' },
  { id: 'mastery-chakula', icon: '🍽️', sw: 'Mtaalamu wa Chakula', en: 'Food Explorer', descSw: 'Jifunze maneno yote ya chakula.', descEn: 'Learn every food word.' },
  { id: 'mastery-wanyama', icon: '🦁', sw: 'Mwongoza Safari', en: 'Safari Guide', descSw: 'Jifunze maneno yote ya wanyama.', descEn: 'Learn every animal word.' },
  { id: 'mastery-biashara', icon: '🛒', sw: 'Bingwa wa Soko', en: 'Market Master', descSw: 'Jifunze maneno yote ya sokoni.', descEn: 'Learn every market word.' },
  { id: 'mastery-salamu', icon: '👋', sw: 'Mwanzo wa Kiswahili', en: 'Swahili Starter', descSw: 'Jifunze salamu zote.', descEn: 'Learn every greeting word.' },
  { id: 'mastery-kila-siku', icon: '🏠', sw: 'Maneno ya Kila Siku', en: 'Everyday Speaker', descSw: 'Jifunze maneno yote ya kila siku.', descEn: 'Learn every everyday word.' },
  { id: 'mastery-safari-hifadhi', icon: '🧭', sw: 'Mlinzi wa Hifadhi', en: 'Park Pathfinder', descSw: 'Jifunze maneno yote ya safari na hifadhi.', descEn: 'Learn every safari and park word.' },
  { id: 'mastery-vitendo', icon: '🎯', sw: 'Mwenye Vitendo', en: 'Action Speaker', descSw: 'Jifunze maneno yote ya vitendo.', descEn: 'Learn every action word.' },
  { id: 'mastery-muda-ratiba', icon: '🕒', sw: 'Mlinzi wa Muda', en: 'Time Keeper', descSw: 'Jifunze maneno yote ya muda na ratiba.', descEn: 'Learn every time and routine word.' },
];

const SHOP_ITEMS = [
  { id: 'theme-ocean', type: 'theme', cost: 80, sw: 'Mandhari ya Bahari', en: 'Ocean Theme', descSw: 'Picha ya pwani, bahari, na mnazi.', descEn: 'Coastline artwork with ocean and palms.' },
  { id: 'theme-savanna', type: 'theme', cost: 80, sw: 'Mandhari ya Savana', en: 'Savanna Theme', descSw: 'Picha ya savana na mti wa mbugani.', descEn: 'Savanna artwork with warm grassland scenery.' },
  { id: 'theme-kilimanjaro', type: 'theme', cost: 120, sw: 'Mandhari ya Kilimanjaro', en: 'Kilimanjaro Theme', descSw: 'Picha ya mlima, theluji, na anga safi.', descEn: 'Mountain artwork with snow and bright sky.' },
  { id: 'theme-zanzibar', type: 'theme', cost: 120, sw: 'Mandhari ya Zanzibar', en: 'Zanzibar Theme', descSw: 'Picha ya pwani, jahazi, na jua la visiwani.', descEn: 'Island artwork with beach, dhow, and sun.' },
  { id: 'theme-dar', type: 'theme', cost: 140, sw: 'Mandhari ya Dar', en: 'Dar Theme', descSw: 'Picha ya majengo ya jiji na bahari usiku.', descEn: 'City skyline artwork with coastal night colors.' },
  { id: 'badge-gold', type: 'badge', cost: 60, sw: 'Fremu ya Dhahabu', en: 'Gold Badge Frame', descSw: 'Pamba beji zako kwa dhahabu.', descEn: 'Dress your badges with a gold frame.' },
  { id: 'badge-kanga', type: 'badge', cost: 90, sw: 'Fremu ya Kanga', en: 'Kanga Badge Frame', descSw: 'Mwonekano wa kanga kwa beji.', descEn: 'A kanga-style badge frame.' },
  { id: 'trail-spark', type: 'effect', cost: 110, sw: 'Mwangaza wa Neno', en: 'Word Spark Trail', descSw: 'Mwangaza mdogo ukipata neno.', descEn: 'A small spark effect when finding words.' },
];

window.NenoSafariContent = {
  CATEGORIES,
  DAILY_WORDS,
  WODS,
  ENCOURAGEMENTS,
  EXTRA_WORDS,
  ADVANCED_WORDS,
  BADGE_DEFS,
  SHOP_ITEMS,
};
})();
